# Generated by Django 5.0.6 on 2024-06-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_playlist_author_song_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='playlist',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
