# Generated by Django 5.0.6 on 2024-06-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlists', '0004_remove_song_playlist_delete_playlist_delete_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('uri', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
